### ISSUE TITLE
Can't login to administrator account

### ISSUE THREAD

**Issue by Manolico** [Yushe/3ch#1]
I tried to leave blank user and place my password from config.php and a lot of combinations but i can't. I really love this script but i cant manage it.

**Comment by Yushe** [comment]
The "PANEL_PASS" in config.php is just the password for deleting posts on the index.

When you run test.php it will create the defualt admin account.
If you used the master branch it would be (If I remember the master branch is full of bugs, wouldn't recommend using):
Username: admin
password: badmin

If your using the releases (you should use these instead of master https://github.com/Yushe/3ch/releases):

Username: admin
Password: guest
